### ISSUE TITLE
首页在线模块崩溃

### ISSUE THREAD

**Issue by huyanghu** [hiliving/superMovie#10]
问题:A WebView method was called on thread 'Chrome_FileThread'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {d8f7413} called on null, FYI main Looper is Looper (main, tid 1) {d8f7413})

网址也打不开

**Comment by hiliving** [comment]
已处理，网站目前有点问题，过段时间上线 @huyanghu
