### ISSUE TITLE
只用下载功能

### ISSUE THREAD

**Issue by zjz930829** [hiliving/superMovie#13]
如果只想用里面的downloadlib，可以实现吗，我导入包后，运行报错，报错的是说so库加载失败，就是在application中初始化的时候失败了，是不是thunder这个包需要配置什么appKey什么之类的，

**Comment by hiliving** [comment]
@zjz930829 不需要appkey,应该是build.gradle里的配置，在app的build.gradle文件里添加
` //过滤掉不支持的平台
    packagingOptions {
        exclude "lib/arm64-v8a/librealm-jni.so"
        exclude "lib/mips/librealm-jni.so"
        exclude "lib/x86/librealm-jni.so"
        exclude "lib/x86_64/librealm-jni.so"
    }

    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a'
        }
    }`
这样应该可以了，参考我的app工程下面的build.gradle.

downloadlib是封装了UI界面等功能的，如果只需要下载，自己定义多任务等功能的话，可以直接引用t hunder,用法参考downloadLib

**Comment by zjz930829** [comment]
我只添加了上面那段，少添加了
splits {
abi {
enable true
reset()
include 'armeabi-v7a'
}
}
这段代码，感谢老铁
