### ISSUE TITLE
不能搜索

### ISSUE THREAD

**Issue by woodytian** [hiliving/superMovie#22]
美版s8+，9.0系统。点击搜索框就退出，100%复现。之前8.0没出过问题。

**Comment by hiliving** [comment]
麻烦提供下log，我这是正常的 @woodytian

**Comment by woodytian** [comment]
@hiliving 这个用什么工具搞?

**Comment by hiliving** [comment]
试下1.2.2版本 @woodytian

**Comment by woodytian** [comment]
@hiliving 新版本彻底不能用了。连不了网。反馈页显示"位于 http://123.207.150.253/ygcms/app/about.html的网页无法加载，因为：
net::ERR_CLEARTEXT_NOT_PERMITTED"

**Comment by hiliving** [comment]
@woodytian  检查下你的网络环境

**Comment by woodytian** [comment]
@hiliving 网络没问题。其他软件都正常上网。开不开vpn都一样。卸载重装也不行。

**Comment by hiliving** [comment]
@woodytian 你是不是在应用设置里，单独关闭了极光影院的网络权限

**Comment by woodytian** [comment]
@hiliving 这个操作太高级了。。。并不会。

**Comment by hiliving** [comment]
突然想起来了，是安卓9.0的限制，默认必须https，我没处理 @woodytian

**Comment by woodytian** [comment]
@hiliving 👌静等更新

**Comment by hiliving** [comment]
@woodytian http://fir.im/btmovie   我先上了个临时版本，下个版本不一定什么时候搞完呢，最近有点忙

**Comment by woodytian** [comment]
ok了。搜索也正常了。thx
