### ISSUE TITLE
追剧神器里选择剧集后点击左上角播放白屏

### ISSUE THREAD

**Issue by OTraveler** [hiliving/superMovie#32]
开发者您好，我的设备也是努比亚Z17S，但是出现了标题所描述的问题，在腾讯视频里不管看的是不是会员视频都会

**Comment by hiliving** [comment]
解析地址好久没更新了，下个版本更新@OTraveler

**Comment by OTraveler** [comment]
> 解析地址好久没更新了，下个版本更新@OTraveler

如果能加入视频小窗悬浮桌面或其它应用上播放就更好了

**Comment by hiliving** [comment]
@OTraveler 好嘞
